### ISSUE TITLE
Vault Reader methods "getImplicit(), getPrefix(), getSuffix()" broken again

### ISSUE THREAD

**Issue by davue** [Odgug/CC-Vault#5]
`getImplicit()`, `getSuffix()` and `getPrefix()` are broken again. Tested on VH `3.15.3`

```
java.lang.NoSuchMethodError: 'iskallia.vault.gear.attribute.VaultGearModifier$AffixCategory iskallia.vault.gear.attribute.VaultGearModifier.getCategory()'
        at net.joseph.ccvault.peripheral.custom.VaultReaderBlockPeripheral.getDisplay(VaultReaderBlockPeripheral.java:162) ~[ccvault-1.1.1-3.14.jar%2362!/:1.1.1-3.14] {re:classloading}
        at net.joseph.ccvault.peripheral.custom.VaultReaderBlockPeripheral.getImplicit(VaultReaderBlockPeripheral.java:276) ~[ccvault-1.1.1-3.14.jar%2362!/:1.1.1-3.14] {re:classloading}
        at net.joseph.ccvault.peripheral.custom.VaultReaderBlockPeripheral$cc$getImplicit92.apply(CC generated method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.call(PeripheralAPI.java:112) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at dan200.computercraft.core.apis.PeripheralAPI.call(PeripheralAPI.java:361) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at dan200.computercraft.core.apis.PeripheralAPI$cc$call50.apply(CC generated method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at dan200.computercraft.core.lua.ResultInterpreterFunction.invoke(ResultInterpreterFunction.java:61) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at cc.tweaked.internal.cobalt.function.ResumableVarArgFunction.invoke(ResumableVarArgFunction.java:77) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at cc.tweaked.internal.cobalt.function.LuaInterpreter.execute(LuaInterpreter.java:506) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at cc.tweaked.internal.cobalt.function.LuaInterpretedFunction.invoke(LuaInterpretedFunction.java:149) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at cc.tweaked.internal.cobalt.LuaThread.loop(LuaThread.java:523) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at cc.tweaked.internal.cobalt.LuaThread$1.run(LuaThread.java:466) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at dan200.computercraft.core.lua.CobaltLuaMachine.lambda$new$1(CobaltLuaMachine.java:80) ~[cc-tweaked-1.18.2-1.101.3.jar%2361!/:1.101.3] {re:classloading}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] {}
        at java.lang.Thread.run(Thread.java:840) [?:?] {}
```

**Comment by davue** [comment]
I quickly looked into it and a simple but not final fix would be to replace `getCategory()` with `getCategories().first()` since the multiple categories are not used yet but might be used in future versions.

**Comment by Odgug** [comment]
fixed version is appending approval on curseforge, ty for reporting
